name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t webapp:${GITHUB_RUN_NUMBER} .

      - name: Run Docker container
        run: docker run --rm -d -p 3000:3000 --name webapp_ctr webapp:${GITHUB_RUN_NUMBER}
